name: License Compliance

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: [ "*" ]
    paths:
      - '**/pom.xml'
      - 'pom.xml'
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven and check dependencies with dash
        run: |
          mvn --batch-mode --update-snapshots verify -P dash
          
      - name: Ensure DEPENDENCIES file is reflecting the current state
        run: |
          mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.summary=DEPENDENCIES-gen -P dash
          diff DEPENDENCIES DEPENDENCIES-gen
          
      - name: upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: 'target/dash/summary'
